pipeline {
    agent {label 'slave1'}
    environment {
        VERSION = '0.2.0'
    }

    stages {
	stage('Git checkout') {
	   steps {
		git([url: 'https://github.com/nikyta384/DevOps_online_Dnipro_2022Q1Q2.git', branch: 'develop'])
	    }
	}
        stage('Build Docker image') {
            steps {
		script {
                    withCredentials([string(credentialsId: 'dockerhub-pwd', variable: 'dockerhubpwd')]) {
                	sh """
			   docker login -u nikyta384 -p ${dockerhubpwd}
                	   sudo docker build -t nikyta384/pavlovskyi-blog:${VERSION} .
                	   sudo docker push
                	   """
		}
            }
        }
        stage('Deploy') {
            steps {
                sh """
               sudo docker pull nikyta384/pavlovskyi-blog:${VERSION}
               sudo docker run -p 80:5000 nikyta384/pavlovskyi-blog:${VERSION}
                """
                }
            }
        }
    }
}
