pipeline {
    agent {label 'slave'}
    environment {
        VERSION = '0.2.0'
    }

    stages {
	stage('Git checkout') {
	   steps {
		script {
		     checkout([$class: 'GitSCM', branches: [[name: '*/develop']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/nikyta384/DevOps_online_Dnipro_2022Q1Q2.git' ]]])
	    }
	}
    }
        stage('Build Docker image') {
            steps {
		script {
                    withCredentials([string(credentialsId: 'dockerhub-pwd', variable: 'dockerhubpwd')]) {
		      dir('pavlovskyi-blog'){
                	sh """
			   ls
			   pwd
			   sudo docker login -u nikyta384 -p ${dockerhubpwd}
			   """
                	   app = docker.build('nikyta384/pavlovskyi-blog:${VERSION}')
                	sh """
			   sudo docker images    
			   sudo docker push nikyta384/pavlovskyi-blog:${VERSION}
                	   """
		    }
		}
            }
	}
    }
        stage('Deploy') {
            steps {
                sh """
               sudo docker pull nikyta384/pavlovskyi-blog:${VERSION}
               sudo docker run -p 80:5000 nikyta384/pavlovskyi-blog:${VERSION}
                """
            }
        }
    }
}
