pipeline {
    agent {label 'slave1'}
    environment {
        VERSION = '0.2.0'
    }

    stages {
        stage('Build Docker image') {
            steps {
                sh """
                sudo docker build -t nikyta384/pavlovskyi-blog:${VERSION} .
                sudo docker push
                """
            }
        }
        stage('Deploy') {
            steps {
                sh """
               sudo docker pull nikyta384/pavlovskyi-blog:${VERSION}
               sudo docker run -p 80:5000 nikyta384/pavlovskyi-blog:${VERSION}
                """
            }
        }
    }
}
